import java.util.Random;
import java.util.Scanner;

/**
 * Problem statement:
 *  Write a java program to Create a class Game, which allows a user to play "Guess the Number"
 *  game once. Game should have the following methods:
 *  (i). Constructor to generate the random number
 *  (ii). takeUserInput() to take a user input of number
 *  (iii). isCorrectNumber() to detect whether the number entered by the user is true or not.
 *  (iv). getter and setter for noOfGuesses
 *  use properties such as noOfGuesses(int) etc. to get this task done!
 * 
 * Author: Md.Noor Hossain Shrabon
 */
public class NumberGuessGame {
    private int randNumber;  // The number generated by computer which to be guessed
    private int noOfGuesses; // Number of attempted by user to guesses
    private Scanner sc;      // Scanner object to take user input

    // Constructor to generate random number
    public NumberGuessGame(){
        Random random = new Random();
        this.randNumber = random.nextInt(100)+1; // random number with in 1 to 100
        this.noOfGuesses = 0; // Initialize the noOfGuesses to 0
        this.sc = new Scanner(System.in); // Initialize the Scanner
    }

    // Create method to take user input
    public int takeUserInput(){
        System.out.print("Enter any number within 1 to 100 :");
        int num = sc.nextInt();
        return num;
    }

    // Method to detect whether the guess by user is true or not
    public boolean isCorrectNumber(int userInput){
        noOfGuesses++;

        if (userInput == randNumber) {
            System.out.println("Congratulation! You guessed the currect number");
            return true;
        }else if (userInput < randNumber) {
            System.out.println("Your guess is too loo!");
            return false;
        }else{
            System.out.println("Your guess is too high!");
            return false;
        }
    }

    // Getter for noOfGuesses
    public int getNoOfGuesses(){
        return noOfGuesses;
    }

    // Setter for noOfGuesses
    public void setNoOfGuesses(int noOfGuesses){
        this.noOfGuesses = noOfGuesses;
    }
    
    public static void main(String[] args) {
        // Create an object of the NumberGuessGame class
        NumberGuessGame game = new NumberGuessGame();
        boolean guessedCorrectly = false;

        System.out.println("Welcome to the Guess the Number Game!");
        System.out.println("I have generated a random number from 1 to 100. Try to guess...");

        while (!guessedCorrectly) {
            int userGuess = game.takeUserInput();
            guessedCorrectly = game.isCorrectNumber(userGuess);
            
        }
        
        int Score = game.getNoOfGuesses();
        System.out.println("Your Score of this game is "+Score);
    }
}
